export const mockLocationsList = [
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Вантовые мосты России',
		link: '/locations/VantovyeMosty',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Башенный комплекс Вовнушки',
		link: '/locations/BashniJegikalIVovnushki',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Богдановичские карьеры',
		link: '/locations/BogdanovichskieKarery',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Гора Большой Тxач',
		link: '/locations/BolshojjTach',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Бухта Новик',
		link: '/locations/BuxtaNovik',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Дивногорье',
		link: '/locations/Divnogore',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Долниа гейзеров',
		link: '/locations/DolinaGejjzerov',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Долина смерти',
		link: '/locations/DolinaSmerti',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Аул-призрак Гамсутль',
		link: '/locations/Gamsutl',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Гора Большое Богдо',
		link: '/locations/GoraBolshoeBogdo',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Гора Эльбрус',
		link: '/locations/GoraJelbrus',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Даргавский некрополь',
		link: '/locations/GorodMertvyx',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Большая Каменная река',
		link: '/locations/KamennyeReki',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Астраханские лотосовые поля',
		link: '/locations/LotosovyePolja',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Вулкан Тятя',
		link: '/locations/VulkanTjatja',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Вулканы Камчатки',
		link: '/locations/VulkanyKamchatki',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Земля Франца-Иосифа',
		link: '/locations/ZemljaFrancaIosifa',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Золотое кольцо',
		link: '/locations/ZolotoeKolco',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Иволгинский дацан',
		link: '/locations/IvolginskijjDacan',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Казанский кремль',
		link: '/locations/KazanskijjKreml',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Калязинская колокольня',
		link: '/locations/KaljazinskajaZatoplennajaKolokolnja',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Кенигсбергский собор',
		link: '/locations/KafedralnyjjSobor',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Красная площадь',
		link: '/locations/KrasnajaPloshhad',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Кроноцкий заповедник',
		link: '/locations/KronockijjZapovednik',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Курильский природный заповедник',
		link: '/locations/KurilskijjPrirodnyjjZapovednik',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Приморский океанариум',
		link: '/locations/PrimorskijjOkeanarium',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Красная поляна',
		link: '/locations/KrasnajaPoljana',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Крепость Нарын-Кала',
		link: '/locations/KrepostNarynKala',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Кунгурская пещера',
		link: '/locations/KungurskajaPeshhera',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Кубанские лавандовые поля',
		link: '/locations/LavandovyePolja',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Кубанские лотосовые поля',
		link: '/locations/KubanskieLotosovyePolja',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Куршская коса (Россия)',
		link: '/locations/KurshskajaKosa',
		activities: ['f', 'f'],
	},
	{
		image: 'images/mocks/pictures/VantovyeMosty/bridge4.png',
		title: 'Куршская коса (Литва)',
		link: '/locations/KurshskajaKosaLitva',
		activities: ['f', 'f'],
	},
];
